Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -10,10 +10,13 @@ phases:
   pre_build:
     commands:
       - echo "Pre-build phase: Setting up dependencies..."
-      - yum update -y    
-      - yum install -y jq 
-      - retry_count=3
-      - for i in $(seq 1 $retry_count); do wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && break || sleep 10; done
+      - yum update -y
+      - yum install -y jq
+      - |
+        retry_count=3
+        for i in $(seq 1 $retry_count); do 
+          wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && break || sleep 10; 
+        done
       - tar xzf apache-maven-3.5.4-bin.tar.gz || true
       - ln -s apache-maven-3.5.4 maven
       - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
@@ -24,11 +27,15 @@ phases:
   build:
     commands:
       - echo "Build phase: Running SonarQube analysis..."
-      - find / -name pom.xml -exec mv {} ./pom.xml \; || true 
+      - find / -name pom.xml -exec mv {} ./pom.xml \; || true
       - mvn sonar:sonar -Dsonar.login=38a3f1733ca11fdd8720e1b236c77112695d2585 -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.projectKey=MueenAfzal_Employee_Management -Dsonar.organization=mueenafzal
       - sleep 5
-      # Check the HTTP response status code directly
-      - if curl -s -o /dev/null -w "%{http_code}" https://sonarcloud.io/api/qualitygates/project_status?projectKey=MueenAfzal_Employee_Management != "200"; then exit 1; fi
+      - |
+        status_code=$(curl -s -o /dev/null -w "%{http_code}" https://sonarcloud.io/api/qualitygates/project_status?projectKey=MueenAfzal_Employee_Management)
+        if [ "$status_code" != "200" ]; then 
+          echo "SonarQube Quality Gate failed. Exiting with error."; 
+          exit 1; 
+        fi
 
 artifacts:
   files:
